name: Verify reCAPTCHA Token

on:
  push:
    branches:
      - main  # 或您希望觸發的其他分支

jobs:
  verify_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify reCAPTCHA token
        run: |
          TOKEN="0cAFcWeA5WNsUX1RH9R6EK4VCwC0GvdbycY11MvB5kdOoHBUsoATmkOc0qdSDx4BlsonJA9MdroD5GLRxgwse1aQGbIEp2s5mstnVvVh2oFbjB1F0nql0Ea2Gds3vQLe1IXLuFOzGquWoGynkIt5RBx-PfNTfGhXjXwCnukAxwMav6WaNvLiLQ7eX1BWEuLfQdyLYL7m6HM1AqvavOj_ykvoh65_XJjKqO_fEix3lUBob4zahKXXoQmSrZ_xA1hORzj4UKBFn0gLPS74CU-v2o5CIx816WlmlLOYeUFetstYyOkZzXSi-mPvw4fWK2YR0T6JINIbtm9OLnA1IUo0oXxX68cGPIHY5RjTECkfvj1mtm40IstIiaTfcvNEV2Mezmo_dtWJ4jZ3cuRIr1HkLhyOAHQgbK4l-K660vtK5HRVT7ZhjVrFC5FZ07b2kE5881OsdUCQdMyD0gIDlB3RTD0Rw-japYH9C8KGNm-vkktfWRyF7ZvFs55fWYdGPdr8Tn5phQYvWRhfoE5bnma_woylHim9uDgjfiwLj90H_4Y_5BQtEOF_P7oWgyxlKrLeXS5W03Sop1Z0EATANmR02OZgPc80LmCp8aYtMsnxp0S8xirJ8b8Eu2NjcKyQO8HIWPUPfI30IP2Y1dRkyb7Q-uHmeOooUSmApgrziEFrK9oyKXFtiXz9biKKd1SAVCPt5tpzoCJ3eSpqk4Xqs4MuDBdAQ1nwWM6vN2qZ-eCBlFrJ-DUzRKMsv2Xtkg-LiW33TrxbKcJkpWZTy_m67x4TyYeiie9vDKFJH9AWhNx9kPXNs68QsqgY3oRJEW6-Zwx4Gglb-qPcef1ecnsxXe1ChMKK32KTscqZ2syfeI_KJ9jwDzU54ZCqm-Seh7fDZT1B5VbCUi9SCqHshuYetnsouQaeuMtmURAg30saZpR8RaCPIPQA8Cl9j-Bpnc-LX-FalooW8OIvQPhzDtiNL6XTKPxBZxz9jhXyCTAyRQJklyf0qpPiRJxrqH3XIHrhw3dqaVRNDqAarSw2OtADtYjAomXXVETzoCzYxZ1v_gO7WVRUS-60r_eGNJqNoSDterm-6Ygrd29ws5vtEK3x-vQpMYuxhN-TyXyW7M33uGRRx8jHM4YdO1vwyT88jPCOl2gQgKVz-RSBWMYKFPUdr5zyfjuDxJSxFolV-sE7NDTuLgqJdsiXskjPd_cWW95rZR1PXiC8r-PRM57_Y-QQQrTeC6Th5Ba561G5D65VRqEOlIF2WwUeoboKXN94abNr30gFhsprrM1rt85H_fIuBCRYBE2ARnK3Jzp1LmVlg2zTOa0rVYjohx7X6kDJ-BDNdVATYTXHNjJzjnxHrfgj2Ma9KI168Ch9iT0WzA0BzOKgwgveMfeUDeK0h1vZx5lQIsLLZjUaxoo0fLmhHKJ4As1XrZLHwhy8BS8Iaw3IeH-k4XSFWkyQaNjrstCXbMh0zDerN6A5uus0U2uXytdEq8_lJKwNiYHj-zxf3Uy8XHJD3zPjsQq-Jpd__oQoFheedsMMaKO0X2GGeJ77gqKN8oakt-zxVMA84Tigx5e-_poO0vrqrwzMamBstfy78"  # 從前端獲取的 token
          SECRET_KEY="${{ secrets.RECAPTCHA_SECRET_KEY }}"  # 從 GitHub Secrets 獲取的秘密金鑰

          RESPONSE=$(curl -s -X POST "https://www.google.com/recaptcha/api/siteverify" \
            -d "secret=$SECRET_KEY&response=$TOKEN")

          echo "Response: $RESPONSE"

          if echo "$RESPONSE" | grep -q '"success": true'; then
            echo "Verification successful"
          else
            echo "Verification failed"
            exit 1
          fi
